sudo: required
services:
  - docker

before_install:
  - docker build -t crhamiltonj/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true crhamiltonj/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: elasticbeanstalk-us-east-2-064448880602
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_EBS_ACCESS_ID
  secret_access_key: $AWS_EBS_SECRET_KEY
  
